### ISSUE TITLE
Make an interface at the plugin installation to set integration variables.

### ISSUE THREAD

**Issue by afshinsadeghi** [OSCOSS/OJSFWplugin#14]
The variables: 
- Editor (FW) URL
- shared Key for interaction authentication

**Comment by afshinsadeghi** [comment]
As hint,  check how other plugins do it. Template files must be added for that with a dialog box to set the variables.

**Comment by s6fikass** [comment]
commit https://github.com/OSCOSS/OJSIntegrationRestAPIplugin/commit/c0eb000d6e681839816af011058470812f7d088f 
![image](https://cloud.githubusercontent.com/assets/19859475/24095416/5c2e4fe6-0d5d-11e7-97cd-781d1c8a12f2.png)

**Comment by johanneswilm** [comment]
This is done and works.
