### ISSUE TITLE
Markdown syntax in README file is broken

### ISSUE THREAD

**Issue by clange** [OSCOSS/OJSFWplugin#30]
… therefore https://github.com/OSCOSS/OJS-Authoring-Integration-plugin doesn't look nice.

**Comment by johanneswilm** [comment]
@clange This has been fixed in the develop branch. Once merges the changes I made while he was on holiday, this should all be fixed. See https://github.com/OSCOSS/OJS-Authoring-Integration-plugin/tree/develop

**Comment by afshinsadeghi** [comment]
@johanneswilm thanks, I was changing it that got your update. I will have the merge now. 
@clange thanks for pointing it out.

**Comment by johanneswilm** [comment]
@sadeghiafshin OK, I see. Yeah the instructions in the README are outdated as well, so it needed updated. The updates are in the pull request as well.

**Comment by johanneswilm** [comment]
Done and fixed
